---
apiVersion: 1

datasources:
  - name: certsuite-overview-datasource
    type: mysql
    url: DB_URL:DB_PORT
    database: certsuite_usage_db
    user: DB_USER
    editable: true
    uid: 0
    orgId: 1
    access: proxy
    secureJsonData:
      password: DB_PASSWORD
      
