name: Daily Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-22.04

    # Global environment variables for the job
    env:
      NUM_DAYS: "1"
      DB_CHOICE: "aws"
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_PORT: ${{ secrets.DB_PORT }}
      CLIENTID: ${{ secrets.CLIENTID }}
      APISECRET: ${{ secrets.APISECRET }}
      BEARERTOKEN: ${{ secrets.BEARERTOKEN }}
      NAMESPACE: ${{ vars.NAMESPACE }}
      REPOSITORY: ${{ vars.REPOSITORY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: List files in the repository
        run: ls -R
      
      - name: Build certsuite-overview project
        run: |
          cd cmd
          go build -o ../certsuite-overview
      
      - name: Verify certsuite-overview exists
        run: |
          if [ ! -f ./certsuite-overview ]; then
            echo "certsuite-overview binary is missing!"
            exit 1
          fi

      - name: Create Prometheus config file
        run: |
          cat <<EOF > ${{ github.workspace }}/prometheus.yml
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'certsuite'
              static_configs:
                - targets: ['127.0.0.1:7000']
          EOF
      
      - name: Check running Docker containers
        run: docker ps

      - name: Start Prometheus
        run: |
          docker run -d --name prometheus -p 9090:9090 -v ${{ github.workspace }}/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
      
      - name: Start Grafana
        run: |
          docker run -d --name=grafana -p 3000:3000 grafana/grafana
      
      - name: Fetch certsuite usage data
        run: ./certsuite-overview fetch

      - name: Run certsuite-overview project
        run: |
          ./certsuite-overview > logs.txt 2>&1 &
          sleep 5
          cat logs.txt

      - name: Check if certsuite-overview is running
        run: |
          if ! pgrep -f "certsuite-overview"; then
            echo "certsuite-overview is NOT running!"
            exit 1
          else
            echo "certsuite-overview is running."
          fi

      - name: Check if port 7000 is in use
        run: netstat -tlnp || ss -tlnp

      - name: Wait for certsuite-overview to start listening
        run: |
          n=0
          until [ $n -ge 5 ]; do
            curl -f http://127.0.0.1:7000/metrics && break
            n=$((n+1))
            echo "Waiting for certsuite-overview to start listening on port 7000... ($n/5)"
            sleep 10
          done
          if [ $n -ge 5 ]; then
            echo "Metrics not available after 5 attempts" && exit 1
          fi

      - name: Check Prometheus logs
        run: docker logs prometheus
        