name: Daily Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-22.04

    # Global environment variables for the job
    env:
      NUM_DAYS: "1"
      DB_CHOICE: "local"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      
      - name: Pre-check API tokens
        run: |
          set -e
          echo "Checking API tokens..."
    
          # Validate connection to the Quay API
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://quay.io/api/v1/" \
            -H "Authorization: Bearer ${{ secrets.BEARERTOKEN }}")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Token pre-check failed! HTTP status: $RESPONSE. Exiting."
            exit 1
          fi

          echo "Token pre-check passed! Connection to Quay API successful."

      - name: List files in the repository
        run: ls -R

      - name: Build certsuite-overview project
        run: |
          cd cmd
          go build -o ../certsuite-overview

      - name: Run the certsuite-overview project
        run: ./certsuite-overview jobs \
          --DB_USER ${{ secrets.DB_USER }} \
          --DB_PASSWORD ${{ secrets.DB_PASSWORD }} \
          --DB_URL ${{ secrets.DB_URL }} \
          --DB_PORT ${{ secrets.DB_PORT }} \
          --DB_NAME ${{ secrets.DB_NAME }} \
          --CLIENTID ${{ secrets.CLIENTID }} \
          --APISECRET ${{ secrets.APISECRET }} \
          --BEARERTOKEN ${{ secrets.BEARERTOKEN }} \
          --NAMESPACE ${{ vars.NAMESPACE }} \
          --REPOSITORY ${{ vars.REPOSITORY }}
