name: Daily Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-22.04

    # Global environment variables for the job
    env:
      NUM_DAYS: "1"
      DB_CHOICE: "aws"
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_PORT: ${{ secrets.DB_PORT }}
      CLIENTID: ${{ secrets.CLIENTID }}
      APISECRET: ${{ secrets.APISECRET }}
      BEARERTOKEN: ${{ secrets.BEARERTOKEN }}
      NAMESPACE: ${{ vars.NAMESPACE }}
      REPOSITORY: ${{ vars.REPOSITORY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: List files in the repository
        run: ls -R
      
      - name: Build certsuite-overview project
        run: |
          cd cmd
          go build -o ../certsuite-overview

      - name: Create Prometheus config file
        run: |
          cat <<EOF > ${{ github.workspace }}/prometheus.yml
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'certsuite'
              static_configs:
                - targets: ['localhost:8080']
          EOF

      - name: Start Prometheus
        run: |
          docker run -d --name prometheus -p 9090:9090 -v ${{ github.workspace }}/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

      - name: Start Grafana
        run: |
          docker run -d --name=grafana -p 3000:3000 grafana/grafana

      - name: Fetch certsuite usage data
        run: ./certsuite-overview fetch

      - name: Run certsuite-overview project
        run: ./certsuite-overview &

      - name: Wait for metrics to be available
        run: sleep 20

      - name: Check Prometheus metrics endpoint
        run: |
          curl -f http://localhost:9090/metrics || (echo "Metrics not available" && exit 1)
